#!/usr/bin/env python3

import cfscrape
from lxml import html 
import argparse
import os

request = cfscrape.create_scraper(delay=10)

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

class Revwho():
    def __init__(self):
        self.row = dict()
        self.terms = list()

    def setTerms(self, terms):
        self.terms = terms

    def search(self):
        for term in self.terms:
            r = request.get(f"https://viewdns.info/reversewhois/?q={term.replace(' ', '+')}")
            root = html.fromstring(r.text)
            ex = '/html/body/font/table[2]/tr[3]/td/font/table'
            if root.xpath(ex):
                for _ in root.xpath(ex)[0].getchildren()[1:]:
                    domain = _.getchildren()[0].text
                    print(domain, _.getchildren()[1].text)
                    if _.getchildren()[1].text:
                        date = _.getchildren()[1].text
                    else:
                        date = " "

                    if _.getchildren()[2].text:
                        registrar = _.getchildren()[2].text
                    else:
                        registrar = ""

                    self.row[domain] = [date, registrar]

        self.total = len(self.row)

    def output(self, outputfile):
        header = f'{self.total} domains found for {", ".join(self.terms)}.'
        header += '\nDomain Name              Creation Date    Registrar'
        with open(outputfile, 'w') as out:
            out.write(header+'\n')
            out.write('='*60+'\n')
            for domain, (date, registrar) in self.row.items():
                out.write("{0}{1:25}{2:17}{3}{4}".format(bcolors.OKGREEN, domain, date, registrar, bcolors.ENDC))
        print()
        print(f'result saved: {outputfile}')

    def verbose(self):
        header = f'{self.total} domains found for {", ".join(self.terms)}.'
        header += '\nDomain Name              Creation Date    Registrar'
        print(bcolors.OKBLUE + header + bcolors.ENDC)
        if self.total: print(bcolors.FAIL + '='*60 + bcolors.ENDC)

        for domain, (date, registrar) in self.row.items():
            print("{0}{1:25}{2:17}{3}{4}".format(bcolors.OKGREEN, domain, date, registrar, bcolors.ENDC))

def banner():
    os.system('clear')
    print(bcolors.HEADER + '''
  https://twitter/0xc0d   _
 _ __ _____   ____      _| |__   ___
| '__/ _ \ \ / /\ \ /\ / / '_ \ / _ \\
| | |  __/\ V /  \ V  V /| | | | (_) |
|_|  \___| \_/    \_/\_/ |_| |_|\___/
    ''' + bcolors.ENDC)

def main():
    desc = "do reverse whois for term(s) specified and returns a list of domains for that term(s). " 

    parser = argparse.ArgumentParser(description=desc)

    parser.add_argument('--terms', '-t', dest='term', nargs='*',
                        help="single term or space separated terms", required=True)

    parser.add_argument('--output', '-o', dest='outputfile', nargs=1,
                        help="Output to save scan results.", required=False)

    parser.add_argument('--quiet', '-q', dest='quiet', action="store_true",
                        help="Enable quiet/silent mode (only show warnings and errors).", required=False)

    args = parser.parse_args()

    if not args.quiet: banner()

    query = Revwho()
    query.setTerms(args.term)
    query.search()
    if not args.quiet: query.verbose()
    if args.outputfile: query.output(args.outputfile[0])

if __name__ == "__main__":
    main()
